export default {
  common: {
    // primaryColor: '#9A37FA',
    fontFamily: 'Roboto, Helvetica, Tahoma, Arial',
  },
  Button: {
    textColorPrimary: '#FFFFFF',
    textColorHoverPrimary: '#FFFFFF',
    textColorPressedPrimary: '#FFFFFF',
    textColorFocusPrimary: '#FFFFFF',
    textColorDisabledPrimary: '#FFFFFF',

    // normal
    rippleColor: '#821BE6FF',
    colorPrimary: '#821BE6FF',
    colorDisabledPrimary: '#821BE6FF',
    textColorTextPrimary: '#821BE6FF',
    textColorGhostPrimary: '#821BE6FF',
    textColorGhostDisabledPrimary: '#821BE6FF',
    borderPrimary: '#821BE6FF',
    borderDisabledPrimary: '#821BE6FF',
    // depth -1
    textColorHover: '#A548FFFF',
    textColorFocus: '#A548FFFF',
    textColorTextHover: '#A548FFFF',
    textColorTextFocus: '#A548FFFF',
    textColorGhostHover: '#A548FFFF',
    textColorGhostFocus: '#A548FFFF',
    colorHoverPrimary: '#A548FFFF',
    colorFocusPrimary: '#A548FFFF',
    textColorTextHoverPrimary: '#A548FFFF',
    textColorTextFocusPrimary: '#A548FFFF',
    textColorGhostHoverPrimary: '#A548FFFF',
    textColorGhostFocusPrimary: '#A548FFFF',
    borderHover: '1px solid #A548FFFF',
    borderFocus: '1px solid #A548FFFF',
    borderFocusPrimary: '1px solid #A548FFFF',
    borderHoverPrimary: '1px solid #A548FFFF',
    // depth 1
    textColorPressed: '#8E23F5FF',
    textColorTextPressed: '#8E23F5FF',
    textColorGhostPressed: '#8E23F5FF',
    colorPressedPrimary: '#8E23F5FF',
    textColorTextPressedPrimary: '#8E23F5FF',
    textColorGhostPressedPrimary: '#8E23F5FF',
    borderPressed: '1px solid #8E23F5FF',
    borderPressedPrimary: '1px solid #8E23F5FF',
  },
  Tabs: {
    tabTextColorActiveLine: '#821BE6FF',
    tabTextColorHoverLine: '#821BE6FF',
    tabTextColorActiveBar: '#821BE6FF',
    tabTextColorHoverBar: '#821BE6FF',
    tabTextColorActiveCard: '#821BE6FF',
    barColor: '#821BE6FF',
  },
  Pagination: {
    //item bg color
    itemColor: '#1C2025',
    itemColorHover: '#1e2328',
    itemColorPressed: '#1e2328',
    itemColorDisabled: '#181b1f',
    buttonColor: '#1C2025',
    buttonColorHover: '#1e2328',
    buttonColorPressed: '#1e2328',
    //item text color
    itemTextColor: '#b1b1b1',
    itemTextColorHover: '#b1b1b1',
    itemTextColorPressed: '#b1b1b1',
    itemTextColorDisabled: '#b1b1b1',
    buttonIconColor: '#b1b1b1',
    buttonIconColorHover: '#b1b1b1',
    buttonIconColorPressed: '#b1b1b1',
    //item border color
    itemBorder: 'none',
    itemBorderHover: 'none',
    itemBorderPressed: 'none',
    itemBorderDisabled: 'none',
    buttonBorder: 'none',
    buttonBorderHover: 'none',
    buttonBorderPressed: 'none',
    //item active color
    itemTextColorActive: '#ffffff',
    itemBorderActive: 'none',
    itemColorActive: '#821BE6FF',
    itemColorActiveHover: '#821BE6FF',
    // itemBorder: 'none',
    // itemColor: '#1C2025',
    // itemTextColor: '#fff',
    // itemBorderHover: 'none',
    // itemColorHover: '#ABA9FF',
    // itemTextColorHover: '#5C1AE5',
    // itemBorderActive: 'none',
    // itemColorActive: '#5C1AE5',
    // itemTextColorActive: '#fff',
    // itemColorActiveHover: '#5C1AE5',
  },
  Spin: {
    textColor: '#821BE6FF',
    color: '#821BE6FF',
  },
  LoadingBar: {
    colorLoading: '#821BE6FF',
  },
  DataTable: {
    loadingColor: '#821BE6FF',
  },
};
