export default {
  common: {
    // primaryColor: '#9A37FA',
    textColor1: '#ffffff', //'rgba(255,255,255,0.9)',
    textColor2: '#ffffff', //'rgba(255,255,255,0.82)',
    bodyColor: 'rgb(16, 16, 20)',
    fontFamily: 'Roboto, sans-serif',

    primaryColor: '#5A1DDD',
    primaryColorHover: 'rgba(90,29,221,0.8)',
    primaryColorPressed: '#8E23F5FF',
  },
  Input: {
    caretColor: '#ffffff',
    color: '#212121',
  },
  Button: {
    heightMedium: '44px',
    textColorPrimary: '#FFFFFF',
    textColorHoverPrimary: '#FFFFFF',
    textColorPressedPrimary: '#FFFFFF',
    textColorFocusPrimary: '#FFFFFF',
    textColorDisabledPrimary: '#FFFFFF',

    // normal
    rippleColor: '#5A1DDD',
    colorPrimary: '#5A1DDD',
    colorDisabledPrimary: 'rgba(90,29,221,0.8)',
    textColorTextPrimary: '#5A1DDD',
    textColorGhostPrimary: '#5A1DDD',
    textColorGhostDisabledPrimary: '#5A1DDD',
    borderPrimary: '#5A1DDD',
    borderRadiusMedium: '8px',
    borderDisabledPrimary: '#5A1DDD',
    // depth -1
    textColorHover: 'rgba(90,29,221,0.8)',
    textColorFocus: 'rgba(90,29,221,0.8)',
    textColorTextHover: 'rgba(90,29,221,0.8)',
    textColorTextFocus: 'rgba(90,29,221,0.8)',
    textColorGhostHover: 'rgba(90,29,221,0.8)',
    textColorGhostFocus: 'rgba(90,29,221,0.8)',
    colorHoverPrimary: 'rgba(90,29,221,0.8)',
    colorFocusPrimary: 'rgba(90,29,221,0.8)',
    textColorTextHoverPrimary: 'rgba(90,29,221,0.8)',
    textColorTextFocusPrimary: 'rgba(90,29,221,0.8)',
    textColorGhostHoverPrimary: 'rgba(90,29,221,0.8)',
    textColorGhostFocusPrimary: 'rgba(90,29,221,0.8)',
    borderHover: '1px solid rgba(90,29,221,0.8)',
    borderFocus: '1px solid rgba(90,29,221,0.8)',
    borderFocusPrimary: '1px solid rgba(90,29,221,0.8)',
    borderHoverPrimary: '1px solid rgba(90,29,221,0.8)',
    // depth 1
    textColorPressed: '#8E23F5FF',
    textColorTextPressed: '#8E23F5FF',
    textColorGhostPressed: '#8E23F5FF',
    colorPressedPrimary: '#8E23F5FF',
    textColorTextPressedPrimary: '#8E23F5FF',
    textColorGhostPressedPrimary: '#8E23F5FF',
    borderPressed: '1px solid #8E23F5FF',
    borderPressedPrimary: '1px solid #8E23F5FF',
  },
  Tabs: {
    tabTextColorActiveLine: '#5A1DDD',
    tabTextColorHoverLine: '#5A1DDD',
    tabTextColorActiveBar: '#5A1DDD',
    tabTextColorHoverBar: '#5A1DDD',
    tabTextColorActiveCard: '#5A1DDD',
    barColor: '#5A1DDD',
  },
  Pagination: {
    //item bg color
    itemColor: '#1C2025',
    itemColorHover: '#1e2328',
    itemColorPressed: '#1e2328',
    itemColorDisabled: '#181b1f',
    buttonColor: '#1C2025',
    buttonColorHover: '#1e2328',
    buttonColorPressed: '#1e2328',
    //item text color
    itemTextColor: '#b1b1b1',
    itemTextColorHover: '#b1b1b1',
    itemTextColorPressed: '#b1b1b1',
    itemTextColorDisabled: '#b1b1b1',
    buttonIconColor: '#b1b1b1',
    buttonIconColorHover: '#b1b1b1',
    buttonIconColorPressed: '#b1b1b1',
    //item border color
    itemBorder: 'none',
    itemBorderHover: 'none',
    itemBorderPressed: 'none',
    itemBorderDisabled: 'none',
    buttonBorder: 'none',
    buttonBorderHover: 'none',
    buttonBorderPressed: 'none',
    //item active color
    itemTextColorActive: '#ffffff',
    itemBorderActive: 'none',
    itemColorActive: '#5A1DDD',
    itemColorActiveHover: '#5A1DDD',
    // itemBorder: 'none',
    // itemColor: '#1C2025',
    // itemTextColor: '#fff',
    // itemBorderHover: 'none',
    // itemColorHover: '#ABA9FF',
    // itemTextColorHover: '#5C1AE5',
    // itemBorderActive: 'none',
    // itemColorActive: '#5C1AE5',
    // itemTextColorActive: '#fff',
    // itemColorActiveHover: '#5C1AE5',
  },
  Spin: {
    textColor: '#5A1DDD',
    color: '#5A1DDD',
  },
  LoadingBar: {
    colorLoading: '#5A1DDD',
  },
  DataTable: {
    thColor: '#1c2025',
    // tdColor: '#1c2025',
    tdColorStriped: '#1c2025',
    loadingColor: '#5A1DDD',
  },
  Dropdown: {
    color: '#18181c',
  },
  Popover: {
    color: '#212121', // --bg-color2
  },
};
